### ISSUE TITLE
Huawei P9+ Mono sensor DNG issue

### ISSUE THREAD

**Issue by sarurururu** [KillerInk/FreeDcam#133]
Hi, in the recent releases of FreeDcam the DNGs saved will become messed up like this:
![Capture](https://user-images.githubusercontent.com/74574559/99324813-ffbe9500-28af-11eb-91a9-f425d9ccfed7.JPG)

It will be solved after switching the "Dual Camera" under settings to color, then back to mono. This problem comes back if I leave the app (even without killing it), e.g. pressing the home button.

Thanks for such a great app!

**Comment by KillerInk** [comment]
hi the problem is caused due settings are not set to the camera. 
its fixed in meantime and with next release its working again

**Comment by sarurururu** [comment]
Thanks, I've just updated to 4.3.16 and it crashes upon starting. It persists after a reboot and re-installation.

**Comment by KillerInk** [comment]
yeah added something stupid. 4.3.17 work again

**Comment by sarurururu** [comment]
The app starts again but the same mono DNG issue is still there...
