### ISSUE TITLE
If FreeDcam remembered ALL last used settings would be 100% perfect (for me)

### ISSUE THREAD

**Issue by JohnSmith6666** [KillerInk/FreeDcam#168]
Wow! Thanks for such a good job.
This is the ONLY ONE APP IN THE WORLD that allow users like me, with CameraAPI1, to play with all manual settings and capture RAW photo.
My phone is not a "Maserati" but with FreeDCam works like a Maserati.
Xiaomi Redmi Note 6pro

But it would be 100% perfect if...

- The APP don't remember last used settings like "Continuous Video" or last used mode on White Balance (but remembers last ISO value), so every time open the APP again I have to configure these settings, and this is very tricky when you are away filming.

This is the MOST IMPORTANT THING, and why I don't use it so often.

Other issues:
- Don't save modified settings on Custom Videoprofiles (but I can modify them on media_profiles.xml file with a code editor)
- I don't need bracketing but is not working
- There's no automatic orientation detection doing a Vertical or Horizontal or Inverted(180 degrees) video or photo
- You can only focus tapping the center of the screen
- Some RAW photos (only sometimes) add a value on DNG baselineexposureoffset, these value must be "0", if not you cannot preview or import to an editor (but I solve it changing it with Exiftool)
- RAW selfie mode produces an inverted photo (180 degrees)- Need for most accurate flash time (longer time)

And again, good job! 
You are great!

PS: I see there's a new release 4.3.51. Not working for me. It crashes trying to open. It only works 4.3.39.
I don't know what has changed from 4.3.39 to 4.3.51 but impossible to run on my device.

**Comment by KillerInk** [comment]
hi, sorry for late reply. but i didnt get noted about this issue.
i personal dont use camera1 api because i have no phone left that support all that stuff.
there are also plans to drop camera1 support because its offical deprecated.
so dont expect much love for camera1

all that not restoring settings should be fixed in meantime.


> Some RAW photos (only sometimes) add a value on DNG baselineexposureoffset, these value must be "0", if not you cannot preview or import to an editor (but I solve it changing it with Exiftool)

https://github.com/KillerInk/FreeDcam/commit/de298ef7a598852e275754e32cc41b8fdba81ad8

> You can only focus tapping the center of the screen

yes thats the intended way with auto. only continouse modes trigger automatic. i know its confusing naming.

> PS: I see there's a new release 4.3.51. Not working for me. It crashes trying to open. It only works 4.3.39.
> I don't know what has changed from 4.3.39 to 4.3.51 but impossible to run on my device.

i need a log. https://github.com/KillerInk/FreeDcam/wiki/How-to-Log
use the second approach and create the log.txt bevor you start freedcam the first time.

> And again, good job!

Haha when it would be so good, you wouldnt have end up here^^

greets

**Comment by JohnSmith6666** [comment]
Thank you for your response,
It's impossible to create a log because I cannot run the app 4.3.51. If the app is not opening there's no way to create a log.
I can only attatch you the error I get when trying to open the app:


java.lang.RuntimeException: Unable to start activity ComponentInfo{troop.com.freedcam/freed.cam.ActivityFreeDcamMain}: java.lang.NullPointerException: found key is null
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.NullPointerException: found key is null
	at freed.settings.SettingsLoader.addSettingElement(SettingsLoader.java:138)
	at freed.settings.SettingsLoader.loadSettings(SettingsLoader.java:60)
	at freed.settings.SettingsStorage.load(SettingsStorage.java:85)
	at freed.settings.SettingsManager.init(SettingsManager.java:146)
	at freed.ActivityAbstract.onCreate(ActivityAbstract.java:83)
	at freed.cam.ActivityFreeDcamMain.onCreate(ActivityFreeDcamMain.java:181)
	at android.app.Activity.performCreate(Activity.java:7224)
	at android.app.Activity.performCreate(Activity.java:7213)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
	... 11 more

(I cannot see the 11 more)
thank you

**Comment by KillerInk** [comment]
> It's impossible to create a log because I cannot run the app 4.3.51. If the app is not opening there's no way to create a log.

the logger is one of the first things that get created. so its already logging when that crash happen.
with a log.txt in /Android/data/troop.com.freedcam/files/ the logger starts to dump the adb log to that file.
but looks like you have access to adb^^

i need to know wich setting it tried to load.
depending on that something is wrong with the featuredetector that fills that setting.

bevor the crash you should see something like this in log
```

troop.com.freedcam D/SettingMode: preview_post_processing_mode [off, OpenGL]
troop.com.freedcam D/SettingMode: focuspeakcolor [Red, Green, Blue, White, Yellow, Magenta, Cyan]
troop.com.freedcam D/SettingMode: horizontlvl []
```

**Comment by JohnSmith6666** [comment]
FreeDcam_release_4.3.52
Well done!
Finally, another working version for my Redmi Note 6 pro with Camera1 api!
Installing OK
It remembers last used settings. OK
Video profile editor Save changed Parameters. OK

Still not working:

-Focus only works at the center of the screen. You cannot tap on other parts to focus.
-When I stop video recording it saves the video OK but the APP shut down 
-Changing shutter-speed value works, but when shutting down and open again the app there's a different shutter-speed value (for example I set 1/60 when I open again the value is 50 ??)
-Question: It is very difficult the app to auto-detect when you hold Horizontal or Vertical? (I know I can do it manually thru settings)
-There's no way to add-change values to take photos in bracketing mode. No lines on settings.


Message whe I finish recording video:
java.lang.IllegalArgumentException: RenderScript Toolkit. histogram supports only ARGB_8888 and ALPHA_8 bitmaps. RGB_565 provided.
	at com.google.android.renderscript.ToolkitKt.validateBitmap(Toolkit.kt:1480)
	at com.google.android.renderscript.ToolkitKt.validateBitmap$default(Toolkit.kt:1477)
	at com.google.android.renderscript.Toolkit.histogram(Toolkit.kt:624)
	at com.google.android.renderscript.Toolkit.histogram$default(Toolkit.kt:622)
	at com.google.android.renderscript.Toolkit.histogram(Unknown Source:2)
	at freed.viewer.screenslide.BitmapLoader.createHistogramm(BitmapLoader.java:68)
	at freed.viewer.screenslide.BitmapLoader.process(BitmapLoader.java:35)
	at freed.image.ImageTask.run(ImageTask.java:21)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

**Comment by KillerInk** [comment]
> Focus only works at the center of the screen. You cannot tap on other parts to focus.

checked it on my good old g3 and evo3d and there its working

> When I stop video recording it saves the video OK but the APP shut down 

the problem is the attached log.didnt expect that the old devices return for a video frame rgb 565

> Changing shutter-speed value works, but when shutting down and open again the app there's a different shutter-speed value (for example I set 1/60 when I open again the value is 50 ??)

cannot check that, no device left that support that. 

> Question: It is very difficult the app to auto-detect when you hold Horizontal or Vertical?

looks like its still not working on camera1

> There's no way to add-change values to take photos in bracketing mode. No lines on settings.

correct. its always using +-1 stop

**Comment by JohnSmith6666** [comment]
Thank you for your comments.
- About focus. I tap at the center of the screen=OK. Then, without moving the phone, I tap on a upper part or lower part of the screen to focus something that is far away from me and is not focused, only if I move the phone and keep the far object at the center of the screen I can focus it.
- About rotation. Other apps use camera1 api and detect orientation. For example: Snap Camera HDR, from https://www.marginz.co.nz/snap/   
Great work!!

**Comment by cyberhardt** [comment]
@KillerInk regarding the program not remembering the configs, it is also happening to me. It keeps resetting the yuv to 1080p and disableing the level meter.
